const dictionnaire = {
  "bonjour": "wakamapo",
  "merci": "wafwako",
  "oui": "Ee",
  "non": "Apana",
  "pardon": "lusa",
  "amour": "Buswe",
  "maison": "njimbo",
  "école": "masomo",
  "manger": "Kudya",
  "boire": "Kutoma",
  "travailler": "Kwigila",
  "marcher": "Kutabula",
  "dormir": "Kulala",
  "écrire": "Kulemba",
  "lire": "Kusoma",
  "fille": "Mwana wa mukaji",
  "garçon": "Mwana mulume",
  "mère": "Mama",
  "maman": "mama",
  "père": "Tata",
  "papa": "Tata",
  "enfant": "Mwana",
  "aimer": "kusanswa",
  "aller": "kwenda",
  "appeler": "kwita",
  "aimer": "kusanswa",
  "aller": "kwenda",
  "appeler": "kwita",
  "arriver": "kufika",
  "ajouter": "kubwanya",
"apprendre": "kufunda",
"apporter": "kuleta",
"admirer": "kutala",
"avancer": "kwenda",
"agir": "kulonga",
"annuler": "kupela",
"abandonner": "kuleka",
"attraper": "kukwata",
"admettre": "kwitaba",
"ancien": "mukulumpe",
"amical": "bulunda",
"attentif": "katentekeji",
"aussi": "kadi",
"bouger": "kujina",
"benir": "kwesela",
"brûler": "kusoka",
"balayer": "kukomba",
"bavarder": "kunenakanya",
"baptiser": "kubatyija",
"bas": "munshi",
"beau": "muyampe",
"béni": "mweselwe",
"bizarre": "bibi",
"blanc": "kitoka",
"bete": "nyema",
"bienveillant": "biyampe",
"bientot": "panopano",
"brusquement": "mu kitulumukila",
"chose": "kintu",
"objet": "kintu",
"cadenas": "loko",
"cassette": "ladiyo",
"canapé": "kityi",
"chaussure": "kilato",
"couteau": "lupete",
"clef": "lufungulo",
"ciel": "madiulu",
"chant": "lwimbo",
"chaise": "kityi",
"chapeau": "kitebo",
"clou": "musumaji",
"célibataire": "kungulume",
"couleur": "musombelo",
"cuisine": "pinshi",
"camion": "kyotoka",
"chaleur": "kyanga",
"canard": "mbata",
"chat": "punshi",
"chave-souris": "popo",
"cheval": "punda",
"chèvre": "mbuji",
"crocodile": "mamba",
"crapaud": "kyula",
"cacher": "kufya",
"content": "sangaji",
"calculer": "kupikula",
"calmer": "kutukija mutyima",
"casser": "kutyumuna",
"ceder": "kupa",
"cesser": "kuleka",
"chanter": "kwimba",
"changer": "kushinta",
"chercher": "kukimba",
"choisir": "kutonga",
"connaitre": "kuyuka",
"compléter": "kubwayna",
"comprendre": "kwivwanija",
"continuer": "kwendeleja",
"cultiver": "kudima",
"couper": "kuketa",
"créer": "kupanga",
"croire": "kukulupila",
"concevoir": "kulama",
"conduire": "kwendeja",
"courir": "kunyema",
"coucher": "kulala",
"craindre": "kogopa",
"combattre": "kulwija",
"chasser": "kupanga",
"chaud": "kyanga",
"cher": "bei",
"court": "kibwipi",
"complet": "kintutulu",
"clair": "kitoka",
"commun": "pamo",
"danger": "kyaka",
"date": "kitatyi",
"délicieux": "bitobala",
"douleur": "misanshi",
"durée": "kitatyi",
"doigt": "munwe",
"don": "kyabuntu",
"dessin": "kifwatulo",
"débuter": "kwanza",
"décéder": "kufwa",
"découvrir": "kusokola",
"dire": "kunena",
"détester": "kushikwa",
"disposer": "kutaluka",
"désier": "kusaka",
"descendre": "kutuka",
"demander": "kulomba",
"dormir": "kulomba",
"discuter": "kwisamba",
"dépasser": "kupita",
"démolir": "kubomona",
"déposer": "kutula",
"dénoncer": "kusapula",
"décéder": "kufwa",
"débarasser": "kuleka",
"demain": "kensha",
"directement": "panopano",
"dehors": "panja",
"doucement": "bityebitye",
"déjà": "kala",
"échanger": "kwisamba",
"échapper": "kunyema",
"éclairer": "kushitunlula",
"écouter": "kwivwana",
"éduquer": "kufundija",
"effectuer": "kulonga",
"effacer": "kujima",
"émettre": "kulupula",
"emprunter": "kwapula",
"égarer": "kunyema",
"élever ": "kumuna",
"empecher": "kujika",
"employer": "kwingidija",
"endormir": "kulala",
"enlever": "kutalula",
"ennuyer": "kukambakanya",
"enseigner": "kufundija",
"entendre": "kwivwana",
"entrer": "kutwela",
"envier": "kusaka",
"envoyer": "kutuma",
"épouser": "kusonga",
"épuiser": "kukoka",
"établir": "kupanga",
"éteindre": "kubula",
"étonner": "kutulumuka",
"étudier": "kufunda",
"évoluer": "kwendelela",
"expliquer": "kushintulula",
"exprimer": "kunena",
"égal": "pamo",
"énervé": "kukalala",
"entier": "kyonso",
"essentiel": "kya mvumbu",
"exact": "kiyampe",
"enocre": "kadi",
"effectivement": "i amo",
"ensemble": "pamo"


  // tu peux en ajouter autant que tu veux...
};

document.getElementById('search').addEventListener('input', function() {
  const mot = this.value.toLowerCase().trim();
  const resultat = dictionnaire[mot];

  const resultDiv = document.getElementById('result');
  if (resultat) {
    resultDiv.innerHTML = `<strong>${mot}</strong> en Kiluba : <em>${resultat}</em>`;
  } else if (mot) {
    resultDiv.innerHTML = `Aucun résultat pour : <strong>${mot}</strong>`;
  } else {
    resultDiv.innerHTML = "";
  }
});













